description: Delaware gross income adjustments sources.
values:
  2021-01-01:
    - pension_contributions
    - self_employment_tax_ald_person
    - alimony_expense
    - de_pension_exclusion

metadata:
  unit: variable
  label: Delaware gross income adjustments sources
  reference:
  - title: PIT-RES_TY22_2022-02_Instructions.pdf
    href: https://revenuefiles.delaware.gov/2022/PIT-RES_TY22_2022-02_Instructions.pdf#page=2
  - title: Delaware Code
    href: https://casetext.com/statute/delaware-code/title-30-state-taxes/part-ii-income-inheritance-and-estate-taxes/chapter-11-personal-income-tax/subchapter-iii-nonresident-individuals/section-1123-delaware-adjusted-gross-income?searchWithin=true&listingIndexId=delaware-code.title-30-state-taxes&q=gross%20income&type=statute&sort=relevance&p=1
