description: Maryland list of AGI subtractions.
values:
  2021-01-01:
    - md_dependent_care_subtraction
    - md_pension_subtraction
    - md_socsec_subtraction
    - md_two_income_subtraction
  2022-01-01:
    - md_dependent_care_subtraction
    - md_pension_subtraction
    - md_socsec_subtraction
    - md_two_income_subtraction
    - md_hundred_year_subtraction

metadata:
  reference:
    - title: MD 2022 Resident Booklet 
      href: https://www.marylandtaxes.gov/forms/22_forms/Resident_Booklet.pdf#page=13
  period: year
  unit: list
  label: Maryland subtractions
