description: Alabama allows for the following itemized deductions.
values:
  2021-01-01:
    - real_estate_taxes
    - charitable_deduction
    - taxsim_tfica
    - al_medical_expense_deduction
    - al_misc_deduction
    - al_mortgage_interest_deduction
    - al_investment_interest_deduction


metadata:
  unit: list
  label: Alabama itemized deductions sources
  reference:
    - title: Code of Alabama Section 40-18-15
      href: https://law.justia.com/codes/alabama/2022/title-40/chapter-18/article-1/section-40-18-15/
    - title: 2022 Schedule A (Form 1040)
      href: https://www.revenue.alabama.gov/ultraviewer/viewer/basic_viewer/index.html?form=2023/01/22f40schabdc_blk.pdf#page=1
    - title: 2021 Schedule A (Form 1040)
      href: https://www.revenue.alabama.gov/ultraviewer/viewer/basic_viewer/index.html?form=2022/06/21f40schabdc_blk.pdf#page=1

