description: California Foster Youth Tax Credit is limited to person between 18 to 25 and has a maximum amount of 1083
brackets:  
  - threshold:  
      2022-01-01: 0  
    amount:  
      2022-01-01: 0  
  - threshold:  
      2022-01-01: 18  
    amount:  
      2022-01-01: 1_176
  - threshold:  
      2022-01-01: 25  
    amount:  
      2022-01-01: 0 
metadata:
  threshold_unit: year
  type: single_amount
  amount_unit: currency-USD
  period: year
  label: California foster youth tax credit base  
  reference:
    - title: California Foster Youth Tax Credit
      href: https://www.ftb.ca.gov/file/personal/credits/foster-youth-tax-credit.html
    - title: 2022 California Earned Income Tax Credit Form
      href: https://www.ftb.ca.gov/forms/2022/2022-3514.pdf#page=4
    #- title: 2021 California Earned Income Tax Credit Form
      #href: https://www.ftb.ca.gov/forms/2021/2021-3514.pdf#page=3
    - title: California Revenue and Taxation Code (R&TC) Section 17052.2
      href: https://casetext.com/statute/california-codes/california-revenue-and-taxation-code/division-2-other-taxes/part-10-personal-income-tax/chapter-2-imposition-of-tax/section-170522-foster-youth-tax-credit-for-qualified-taxpayers#:~:text=Section%2017052.2%20%2D%20Foster%20youth%20tax%20credit%20for%20qualified%20taxpayers%20(a,determined%20under%20paragraph%20(2)

