description: Montana provides the following base amount per child under the child tax credit.
brackets:
  - threshold:
      2021-11-01: 0
    amount:
      2023-01-01: 1_200
      2021-11-01: 3_600
      2020-01-01: 2_000
  - threshold:
      2021-11-01: 5
    amount:
      2023-01-01: 0
      2021-11-01: 3_600
      2020-01-01: 2_000 
  - threshold:
      2021-11-01: 6
    amount:
      2021-11-01: 3_000
      2020-01-01: 2_000
  - threshold:
      2021-11-01: 17
    amount:
      2021-11-01: 0
      2020-01-01: 0
metadata:
  type: single_amount
  threshold_unit: year
  amount_unit: currency-USD
  period: year
  name: montana_child_tax_credit_base
  label: "Montana child tax credit base"
  reference:
    - title: 2023 Montana Legislature, House Bill No. 268, Section 1, 7 (c)
      href: https://leg.mt.gov/bills/2023/billhtml/HB0268.htm
    - title: Federal Tax Credit, page 3-4
      href: https://leg.mt.gov/content/Committees/Interim/2021-2022/Economic%20Affairs/Meetings/November%202021/Federal-Tax-Credits.pdf

