description: Montana provides the following base amount per child under the child tax credit.
values:
  2023-01-01: 1_200
metadata:
  units: currency-USD
  period: year
  label: Montana child tax credit base
  reference:
    - title: 2023 Montana Legislature, House Bill No. 268, Section 1, 7 (c)
    - href: https://leg.mt.gov/bills/2023/billhtml/HB0268.htm