description: Base income of parent contribution
brackets:
  - threshold:
      2023-01-01: -.inf
    amount:
      2023-01-01: -750
  - threshold:
      2023-01-01: -3_409
    amount:
      2023-01-01: 0
  - threshold:
      2023-01-01: 17_501
    amount:
      2023-01-01: 3_850
  - threshold:
      2023-01-01: 22_001
    amount:
      2023-01-01: 4_975
  - threshold:
      2023-01-01: 26_501
    amount:
      2023-01-01: 6_280
  - threshold:
      2023-01-01: 31_001
    amount:
      2023-01-01: 7_810
  - threshold:
      2023-01-01: 35_501
    amount:
      2023-01-01: 9_610
metadata:
  type: single_amount
  rate_unit: /1
  threshold_unit: /1
  label: Base income of parent contribution
  reference:
    - title: THE EFC FORMULA, 2022–2023
      href: https://fsapartners.ed.gov/site/default/files/2021-08/2223EFCFormulaGuide.pdf#page=29
