description: Hawaii extends this amount for each exemption under the income tax credit for low-income household renters.
values:
  2021-01-01: 50

metadata:
  unit: currency-USD
  period: year
  label: Hawaii income tax credit for low-income household renters base amount
  reference:
    - title: Hawaii Income Tax Law, HRS ยง235-55.7 ยง18-235-55.7 (b)
      href: https://files.hawaii.gov/tax/legal/har/har_235.pdf#page=105
  reference:
    - title: 2021 Hawaii Revised Statutes ยง235-55.7 (b)
      href: https://law.justia.com/codes/hawaii/2021/title-14/chapter-235/section-235-55-7/