description: New Hampshire provides this base exemption for taxpayers.
metadata:
  unit: currency-USD
  label: New Hampshire base exemption amount
  reference: 
    - title: TITLE V - TAXATION - CHAPTER 77 - TAXATION OF INCOMES - Section 77:5
      href: https://www.gencourt.state.nh.us/rsa/html/V/77/77-5.htm
values:
  2022-01-01: 2_400
  2027-01-01: 0